name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i /path/to/your-key.pem ubuntu@<EC2-PUBLIC-IP> <<EOF
            cd /home/ubuntu/fastapi-book-project
            git pull
            sudo systemctl restart fastapi
          EOF
