name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH
      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 18.119.104.183 >> ~/.ssh/known_hosts

      # Step 3: Deploy application
      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@18.119.104.183 <<EOF
            cd /home/ubuntu/fastapi-book-project
            git pull
            sudo systemctl restart fastapi
          EOF
