name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.13.1
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.1

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Deploy the application using Uvicorn
      - name: Deploy application
        run: |
          echo "Starting deployment..."
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
